name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ec2-13-60-249-109.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: Deploy via rsync
      run: |
        rsync -avz --exclude '.git*' ./ ec2-user@ec2-13-60-249-109.eu-north-1.compute.amazonaws.com:/home/ec2-user/Bilingual-Buddy
