name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ec2-13-60-249-109.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy Code to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@ec2-13-60-249-109.eu-north-1.compute.amazonaws.com "cd ~/Bilingual-Buddy && git pull origin main && pm2 restart all || npm install && npm run build && pm2 start npm --name bilingual -- run start"
